name: SkincareArtist
favicon: null
layout_spectrum: 0.8853490718174726
typography_spectrum: 0.073872662615031
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.033134221797809005
  lightness: 0.34719047718681395
  saturation: 0.08835941436700523
  rhythmicContrast: 0.4869129394646734
purpose: []
