name: SkincareArtist
favicon: null
layout_spectrum: 1
typography_spectrum: 0.39651
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c90054'
    - '#d7b6bc'
    - '#8b7875'
    - '#007999'
    - '#130e0d'
  brandStrength: 0.033134221797809005
  lightness: 0.34719047718681395
  saturation: 0.08835941436700523
  rhythmicContrast: 0.75
purpose: []
